baseURL = 'https://streamfigyelo.hu/'
title = 'Stream Figyelő'
theme = "github.com/adityatelange/hugo-PaperMod"

defaultContentLanguage = 'hu'
languageCode = 'hu-hu'

[languages.hu]
    languageName = 'Magyar'
    weight = 1

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    defaultTheme = "dark"
    description = "Stream Figyelő - Kritikák, streaming hírek és minden, ami mozi."
    images = ["/images/og-image.png"]
    copyright = "© 2026 Stream Figyelő"
    categories = "Kategóriák"
    tags = "Címkék"
    archive = "Archívum"
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    showCodeCopyButtons = true

    [params.assets]
        favicon = "/images/favicon.png"
        favicon16x16 = "/images/favicon.png"
        favicon32x32 = "/images/favicon.png"
        apple_touch_icon = "/images/favicon.png"

    # Ez a rész KELL, hogy a Hugo aktiválja a kezdőlapi blokkot
    [params.homeInfoParams]
        Title = "Aktiválva" 

    [params.shareButtons]
        facebook = true
        twitter = true
        reddit = true

    [params.analytics.goatcounter]
        code = "streamfigyelo"

    [[params.socialIcons]]
        name = "facebook"
        url = "https://facebook.com/streamfigyelo"

# MENÜK
[[menu.main]]
    identifier = "posts"
    name = "Posztok"
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "categories"
    name = "Kategóriák"
    url = "/categories/"
    weight = 20

[[menu.main]]
    identifier = "search"
    name = "Keresés"
    url = "/search/"
    weight = 30

[[menu.main]]
    identifier = "impresszum"
    name = "Impresszum"
    url = "/impresszum/"
    weight = 40

[[menu.main]]
    identifier = "privacy"
    name = "Adatkezelés"
    url = "/adatkezelesi-tajekoztato/"
    weight = 50

[outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["HTML"]
    section = ["HTML"]
