baseURL = 'https://streamfigyelo.hu/'
languageCode = 'hu-hu'
title = 'Stream FigyelÅ‘'
theme = "PaperMod"

[params]
    defaultTheme = "dark" # Vagy "light", ha a fehÃ©ret szereted
    showCodeCopyButtons = true
    
    [params.homeInfoParams]
        Title = "Ãœdv a Stream FigyelÅ‘n! ðŸ‘‹"
        Content = "HÃ­rek, tesztek Ã©s minden, ami streaming."

[[menu.main]]
    identifier = "posts"
    name = "Posztok"
    url = "/posts/"
    weight = 10
