baseURL = 'https://streamfigyelo.hu/'
languageCode = 'hu-hu'
title = 'Stream Figyel≈ë'
theme = "github.com/adityatelange/hugo-PaperMod"

# Ez a r√©sz mondja meg a Cloudflare-nek, hogy t√∂ltse le a t√©m√°t
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
    defaultTheme = "dark"
    showCodeCopyButtons = true
    
    [params.homeInfoParams]
        Title = "Streaming. Sebess√©g. Sztorik. üçø"
        Content = "Ne pazarold az id≈ëd k√∂z√©pszer≈± filmekre. Megkeress√ºk neked a val√≥di gy√∂ngyszemeket a streaming tenger√©ben, √©s odal√©p√ºnk a g√°zra, ha F1-r≈ël van sz√≥."

    [[params.socialIcons]]
        name = "facebook"
        url = "https://facebook.com/streamfigyelo"

[[menu.main]]
    identifier = "posts"
    name = "Posztok"
    url = "/posts/"
    weight = 10

[outputs]
    home = ["HTML", "RSS", "JSON"]
