baseURL = 'https://streamfigyelo.hu/'
languageCode = 'hu-hu'
title = 'Stream Figyel≈ë'
theme = ["github.com/adityatelange/hugo-PaperMod"]

# Ez a r√©sz mondja meg a Cloudflare-nek, hogy t√∂ltse le a t√©m√°t
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
    defaultTheme = "dark"
    showCodeCopyButtons = true
    
    [params.homeInfoParams]
        Title = "√údv a Stream Figyel≈ën! üëã"
        Content = "H√≠rek, tesztek √©s minden, ami streaming."

[[menu.main]]
    identifier = "posts"
    name = "Posztok"
    url = "/posts/"
    weight = 10
